meta_product_name: "LJM Web Development"
meta_title: "LJM Web Development - Full Stack Developer Ruby on Rails"
meta_description: "Front-End Back-End Full-Stack Developer. Specialized in CSS HTML ERB RUBY RAILS"
meta_image: "information-page.PNG" 
